from .models import Job


FULL_TIME_JOBS = [
    {"title": "Python Backend Developer", "company": "NovaStack Technologies", "location": "Hyderabad / Hybrid", "job_type": Job.JobType.FULL_TIME, "salary_min": 600000, "salary_max": 1000000, "required_skills": ["Python", "Django", "REST API", "PostgreSQL", "Docker"], "description": "Build and maintain scalable backend services using Python and Django. Work with frontend developers to develop REST APIs and integrate PostgreSQL databases.", "requirements": "Strong Python fundamentals, Django or Django REST Framework, PostgreSQL, REST APIs, Git and Docker."},
    {"title": "QA Automation Engineer", "company": "TechOrbit Solutions", "location": "Bengaluru / Hybrid", "job_type": Job.JobType.FULL_TIME, "salary_min": 500000, "salary_max": 900000, "required_skills": ["Python", "Selenium", "Playwright", "Pytest", "API Testing"], "description": "Develop automated testing frameworks and ensure the quality of web applications and REST APIs.", "requirements": "Python programming, Selenium or Playwright, Pytest, API testing and basic SQL."},
    {"title": "Full-Stack Python Developer", "company": "CloudNova Labs", "location": "Remote", "job_type": Job.JobType.FULL_TIME, "salary_min": 800000, "salary_max": 1400000, "required_skills": ["Python", "Django", "React", "PostgreSQL", "REST API"], "description": "Develop complete web applications using React on the frontend and Python/Django on the backend.", "requirements": "Python and Django, React and JavaScript, PostgreSQL, REST APIs and Git."},
    {"title": "Data Analyst", "company": "DataPulse Analytics", "location": "Pune / Hybrid", "job_type": Job.JobType.FULL_TIME, "salary_min": 500000, "salary_max": 800000, "required_skills": ["Python", "SQL", "Pandas", "Excel", "Power BI"], "description": "Analyze business data and create dashboards that help teams make data-driven decisions.", "requirements": "SQL, Python/Pandas, Excel, data visualization and Power BI or Tableau."},
    {"title": "Django Developer", "company": "ByteBridge Technologies", "location": "Chennai / On-site", "job_type": Job.JobType.FULL_TIME, "salary_min": 600000, "salary_max": 1100000, "required_skills": ["Python", "Django", "DRF", "PostgreSQL", "Redis"], "description": "Develop secure and scalable web applications using Django and Django REST Framework.", "requirements": "Python, Django, REST APIs, PostgreSQL. Redis and Celery knowledge is a plus."},
    {"title": "Machine Learning Engineer", "company": "AIForge Systems", "location": "Bengaluru / Remote", "job_type": Job.JobType.FULL_TIME, "salary_min": 900000, "salary_max": 1600000, "required_skills": ["Python", "Machine Learning", "Pandas", "Scikit-learn", "SQL"], "description": "Build and deploy machine learning models for real-world business applications.", "requirements": "Python, machine learning fundamentals, Pandas and NumPy, Scikit-learn and SQL."},
    {"title": "DevOps Engineer", "company": "InfraSphere Technologies", "location": "Hyderabad / Hybrid", "job_type": Job.JobType.FULL_TIME, "salary_min": 700000, "salary_max": 1300000, "required_skills": ["Linux", "Docker", "Kubernetes", "AWS", "CI/CD"], "description": "Manage cloud infrastructure and automate software deployment pipelines.", "requirements": "Linux, Docker, AWS, CI/CD and Kubernetes."},
    {"title": "Frontend Developer", "company": "PixelCraft Technologies", "location": "Mumbai / Hybrid", "job_type": Job.JobType.FULL_TIME, "salary_min": 600000, "salary_max": 1200000, "required_skills": ["React", "JavaScript", "HTML", "CSS", "TypeScript"], "description": "Build responsive and interactive web applications using modern frontend technologies.", "requirements": "React, JavaScript, HTML/CSS and Git. TypeScript is a plus."},
    {"title": "Software Engineer", "company": "CodeSphere Innovations", "location": "Gurugram / Hybrid", "job_type": Job.JobType.FULL_TIME, "salary_min": 700000, "salary_max": 1200000, "required_skills": ["Python", "Java", "SQL", "Git", "REST API"], "description": "Design, develop, test and maintain software applications for enterprise customers.", "requirements": "Strong programming fundamentals, Python or Java, SQL, REST APIs and Git."},
    {"title": "Backend API Engineer", "company": "DevMatrix Technologies", "location": "Noida / Remote", "job_type": Job.JobType.FULL_TIME, "salary_min": 800000, "salary_max": 1300000, "required_skills": ["Python", "FastAPI", "PostgreSQL", "REST", "Docker"], "description": "Design high-performance REST APIs and backend services using Python and FastAPI.", "requirements": "Python, FastAPI, PostgreSQL, REST APIs and Docker."},
]
