from .models import Job


INTERNSHIPS = [
    {"title": "Python Developer Intern", "company": "CodeNest Labs", "location": "Hyderabad / Hybrid", "job_type": Job.JobType.INTERNSHIP, "salary_min": 15000, "salary_max": 25000, "required_skills": ["Python", "Django", "SQL", "Git"], "description": "Work with the backend team to develop Python and Django applications.", "requirements": "Basic Python, interest in Django, SQL and Git. You will develop small features, APIs and tests."},
    {"title": "QA Automation Intern", "company": "QualitySphere Technologies", "location": "Bengaluru / Hybrid", "job_type": Job.JobType.INTERNSHIP, "salary_min": 12000, "salary_max": 20000, "required_skills": ["Python", "Selenium", "Pytest", "API Testing"], "description": "Learn and implement automated testing for web and API-based applications.", "requirements": "Interest in Python, Selenium, Pytest, API testing and defect reporting."},
    {"title": "React Developer Intern", "company": "WebNova Labs", "location": "Remote", "job_type": Job.JobType.INTERNSHIP, "salary_min": 15000, "salary_max": 25000, "required_skills": ["React", "JavaScript", "HTML", "CSS", "Git"], "description": "Build responsive web interfaces and integrate them with backend APIs.", "requirements": "Coursework or projects using React, JavaScript, HTML, CSS and Git."},
    {"title": "Data Analyst Intern", "company": "InsightGrid Analytics", "location": "Bengaluru / Hybrid", "job_type": Job.JobType.INTERNSHIP, "salary_min": 12000, "salary_max": 22000, "required_skills": ["Python", "SQL", "Excel", "Pandas", "Power BI"], "description": "Analyze datasets and create reports and dashboards for business teams.", "requirements": "SQL, Excel, Python/Pandas and an interest in data visualization."},
    {"title": "Full-Stack Developer Intern", "company": "StackWave Technologies", "location": "Hyderabad / Remote", "job_type": Job.JobType.INTERNSHIP, "salary_min": 15000, "salary_max": 25000, "required_skills": ["Python", "Django", "React", "PostgreSQL"], "description": "Work on both frontend and backend components of production-style web applications.", "requirements": "Basic Python, Django, React and PostgreSQL knowledge."},
    {"title": "Machine Learning Intern", "company": "NeuralPeak AI", "location": "Bengaluru / Hybrid", "job_type": Job.JobType.INTERNSHIP, "salary_min": 20000, "salary_max": 30000, "required_skills": ["Python", "NumPy", "Pandas", "Scikit-learn", "ML"], "description": "Assist ML engineers in preparing datasets, training models and evaluating experiments.", "requirements": "Python, NumPy, Pandas, Scikit-learn and machine learning fundamentals."},
    {"title": "Backend Developer Intern", "company": "APIWorks Technologies", "location": "Pune / Hybrid", "job_type": Job.JobType.INTERNSHIP, "salary_min": 15000, "salary_max": 25000, "required_skills": ["Python", "FastAPI", "PostgreSQL", "REST API"], "description": "Develop backend APIs and database integrations using Python.", "requirements": "Python, REST API concepts, PostgreSQL and a willingness to learn FastAPI."},
    {"title": "DevOps Intern", "company": "CloudPilot Systems", "location": "Chennai / Remote", "job_type": Job.JobType.INTERNSHIP, "salary_min": 15000, "salary_max": 25000, "required_skills": ["Linux", "Docker", "AWS", "GitHub Actions"], "description": "Assist the DevOps team with cloud deployments, monitoring and CI/CD automation.", "requirements": "Basic Linux, Docker, AWS and GitHub Actions knowledge."},
    {"title": "Python Automation Intern", "company": "AutomateIQ Labs", "location": "Hyderabad / Hybrid", "job_type": Job.JobType.INTERNSHIP, "salary_min": 12000, "salary_max": 20000, "required_skills": ["Python", "Selenium", "Pytest", "Automation"], "description": "Create Python automation scripts for repetitive business and testing workflows.", "requirements": "Python basics, Selenium, Pytest and interest in automation."},
    {"title": "Software Engineering Intern", "company": "BrightCode Technologies", "location": "Bengaluru / On-site", "job_type": Job.JobType.INTERNSHIP, "salary_min": 18000, "salary_max": 28000, "required_skills": ["Python", "Java", "SQL", "Git"], "description": "Work alongside software engineers on application development and debugging.", "requirements": "Programming fundamentals, Python or Java, SQL and Git."},
    {"title": "SQL & Data Engineering Intern", "company": "DataBridge Systems", "location": "Remote", "job_type": Job.JobType.INTERNSHIP, "salary_min": 15000, "salary_max": 25000, "required_skills": ["SQL", "Python", "PostgreSQL", "ETL"], "description": "Assist with data pipelines, SQL queries and database operations.", "requirements": "SQL, Python, PostgreSQL and an interest in ETL or data engineering."},
    {"title": "UI/UX Developer Intern", "company": "DesignStack Studio", "location": "Mumbai / Hybrid", "job_type": Job.JobType.INTERNSHIP, "salary_min": 10000, "salary_max": 18000, "required_skills": ["HTML", "CSS", "JavaScript", "Figma"], "description": "Design and implement user-friendly interfaces for web applications.", "requirements": "HTML, CSS, JavaScript, Figma and a portfolio or coursework."},
    {"title": "API Testing Intern", "company": "TestGrid Solutions", "location": "Hyderabad / Remote", "job_type": Job.JobType.INTERNSHIP, "salary_min": 12000, "salary_max": 20000, "required_skills": ["Python", "Postman", "REST API", "Pytest"], "description": "Test REST APIs and develop automated API test suites.", "requirements": "REST API concepts, Postman, Python and Pytest."},
    {"title": "Cloud Engineering Intern", "company": "SkyLayer Technologies", "location": "Pune / Hybrid", "job_type": Job.JobType.INTERNSHIP, "salary_min": 15000, "salary_max": 25000, "required_skills": ["AWS", "Linux", "Docker", "Python"], "description": "Assist cloud engineers with application deployment, monitoring and infrastructure automation.", "requirements": "AWS, Linux, Docker and Python basics."},
    {"title": "Web Developer Intern", "company": "DevLaunch Labs", "location": "Remote", "job_type": Job.JobType.INTERNSHIP, "salary_min": 12000, "salary_max": 20000, "required_skills": ["HTML", "CSS", "JavaScript", "React", "Git"], "description": "Develop responsive web pages and integrate frontend components with REST APIs.", "requirements": "HTML, CSS, JavaScript, React and Git fundamentals."},
]
