# Generated by Django 5.1.7 on 2026-09-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
